---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: metabase
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - image: metabase/metabase:latest
          name: metabase
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
            - mountPath: /usr/share/zoneinfo/Asia/Shanghai
              name: timezone
          env:
            - name: TZ
              value: 'Asia/Shanghai'
            - name: MB_DB_TYPE
              value: 'mysql'
            - name: MB_DB_HOST
              value: 'mysql'
            - name: MB_DB_DBNAME
              value: 'metabase'
            - name: MB_DB_PORT
              value: '3306'
            - name: MB_DB_USER
              # value: 'root'
              value: 'metabase'
            - name: MB_DB_PASS
              # value: 'nv4C^eW5uX!p'
              value: '!80qPCatcBnH'
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: metabase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: metabase
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.40
          name: mysql
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'nv4C^eW5uX!p'
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: metabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: metabase
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
