---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf
  namespace: mobsf
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mobsf
  template:
    metadata:
      labels:
        app: mobsf
    spec:
      containers:
        - image: opensecurity/mobile-security-framework-mobsf:latest
          name: mobsf
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mobsf
  namespace: mobsf
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: mobsf
---